
import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'hi' | 'mr';

// Define language context type
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Create language context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Jal Mitra Network',
    'app.tagline': 'Every drop counts—use water wisely',
    'nav.home': 'Home',
    'nav.waterQuality': 'Water Quality',
    'nav.agriculture': 'Agriculture',
    'nav.education': 'Education',
    'nav.community': 'Community',
    'nav.darkMode': 'Dark Mode',
    'stats.waterCrisis': 'Water Crisis',
    'stats.population': '600 million Indians face high water stress',
    'stats.groundwater': '70% of India\'s water is contaminated',
    'stats.farmers': '80% of freshwater is used for agriculture',
    'home.hero.title': 'Join the Movement for Water Conservation',
    'home.hero.subtitle': 'Learn, engage, and take action to protect India\'s water resources',
    'home.hero.cta': 'Get Started',
    'home.hero.learnMore': 'Learn More',
    'home.features.title': 'Our Mission',
    'home.features.education': 'Education',
    'home.features.education.desc': 'Learn about water conservation and sustainable practices',
    'home.features.tracking': 'Track Quality',
    'home.features.tracking.desc': 'Monitor water quality in your area',
    'home.features.community': 'Community',
    'home.features.community.desc': 'Share stories and connect with others',
    'home.features.agriculture': 'Agriculture',
    'home.features.agriculture.desc': 'Discover drought-resistant farming techniques',
    'wqi.title': 'Water Quality Index',
    'wqi.description': 'Track the quality of water in different regions',
    'community.title': 'Community Stories',
    'community.subtitle': 'Real people making a difference',
    'community.join': 'Join The Movement',
    'community.pledge': 'Take the Pledge',
    'community.name': 'Name',
    'community.email': 'Email',
    'community.yourName': 'Your name',
    'community.yourEmail': 'Your email',
    'community.takePledge': 'Take the Pledge',
    'community.pledgeDesc': 'Take the pledge to conserve water and become part of our growing community of water stewards.',
    'community.communities': 'Communities Engaged',
    'community.litersSaved': 'Liters Saved',
    'community.farmers': 'Farmers Supported',
    'community.schools': 'School Programs',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'education.title': 'Education Resources',
    'education.description': 'Education is key to creating lasting change in water conservation practices. Our resources are designed for students, teachers, and communities to learn about water issues and solutions.',
    'education.materials': 'Educational Materials',
    'education.quiz.title': 'Water Conservation Quiz',
    'education.quiz.description': 'Test your knowledge about water conservation and learn ways to reduce your water footprint.',
    'education.quiz.start': 'Start Quiz',
    'education.quiz.next': 'Next Question',
    'education.quiz.previous': 'Previous Question',
    'education.quiz.submit': 'Submit Answers',
    'education.quiz.correct': 'Correct!',
    'education.quiz.incorrect': 'Incorrect!',
    'education.quiz.tryAgain': 'Try again to learn more!',
    'education.quiz.wellDone': 'Well done!',
    'education.quiz.yourScore': 'Your score:',
    'education.quiz.q1': 'How much of the Earth\'s water is freshwater and accessible for human use?',
    'education.quiz.q1.a': 'About 70%',
    'education.quiz.q1.b': 'About 30%',
    'education.quiz.q1.c': 'Less than 1%',
    'education.quiz.q1.d': 'About 10%',
    'education.quiz.q1.correct': 'c',
    'education.quiz.q2': 'Which sector consumes the most water in India?',
    'education.quiz.q2.a': 'Industry',
    'education.quiz.q2.b': 'Agriculture',
    'education.quiz.q2.c': 'Domestic use',
    'education.quiz.q2.d': 'Energy production',
    'education.quiz.q2.correct': 'b',
    'education.quiz.q3': 'Which of these is NOT a water conservation method?',
    'education.quiz.q3.a': 'Rainwater harvesting',
    'education.quiz.q3.b': 'Drip irrigation',
    'education.quiz.q3.c': 'Flood irrigation',
    'education.quiz.q3.d': 'Water recycling',
    'education.quiz.q3.correct': 'c',
    'education.quiz.q4': 'About how many people in India lack access to clean water?',
    'education.quiz.q4.a': '100 million',
    'education.quiz.q4.b': '200 million',
    'education.quiz.q4.c': '50 million',
    'education.quiz.q4.d': '80 million',
    'education.quiz.q4.correct': 'a',
    'education.quiz.q5': 'Which of the following is a major cause of water pollution in India?',
    'education.quiz.q5.a': 'Industrial waste',
    'education.quiz.q5.b': 'Agricultural runoff',
    'education.quiz.q5.c': 'Untreated sewage',
    'education.quiz.q5.d': 'All of the above',
    'education.quiz.q5.correct': 'd',
    'cta.join': 'Join the Movement to Save Water Today',
    'agriculture.title': 'Sustainable Agriculture',
    'agriculture.description': 'Agriculture is the largest consumer of freshwater in India, accounting for over 80% of water usage. Our sustainable agriculture resources help farmers implement water-efficient practices while maintaining crop yields.',
    'agriculture.techniques': 'Drought-Resistant Farming Techniques',
    'agriculture.drip': 'Drip Irrigation',
    'agriculture.drip.desc': 'Saves up to 60% water compared to flood irrigation by delivering water directly to plant roots.',
    'agriculture.mulching': 'Mulching',
    'agriculture.mulching.desc': 'Reduces evaporation, suppresses weeds, and improves soil health.',
    'agriculture.crops': 'Drought-Resistant Crops',
    'agriculture.crops.desc': 'Varieties that require less water and can withstand dry periods.',
    'agriculture.rainwater': 'Rainwater Harvesting',
    'agriculture.rainwater.desc': 'Collecting and storing rainwater for irrigation during dry periods.',
    'agriculture.network': 'Our network connects farmers with agricultural experts who provide guidance on implementing these techniques based on local conditions and available resources.',
    'waterquality.title': 'Water Quality',
    'waterquality.description': 'Monitoring water quality is essential for ensuring the health and safety of communities. Our Water Quality Index (WQI) provides real-time data on water quality in different regions across India.',
    'waterquality.understanding': 'Understanding Water Quality Index',
    'waterquality.understanding.desc': 'The Water Quality Index is a composite measure that indicates the overall quality of water in a specific region. It takes into account various parameters such as:',
    'waterquality.parameters.ph': 'pH levels',
    'waterquality.parameters.oxygen': 'Dissolved oxygen',
    'waterquality.parameters.bod': 'Biochemical oxygen demand',
    'waterquality.parameters.bacteria': 'Total coliform bacteria',
    'waterquality.parameters.nutrients': 'Nitrates and phosphates',
    'waterquality.parameters.turbidity': 'Turbidity',
    'waterquality.parameters.tds': 'Total dissolved solids',
    'feedback.title': 'Your Feedback Matters',
    'feedback.description': 'Help us improve our water conservation efforts with your valuable input.',
    'feedback.name': 'Name',
    'feedback.email': 'Email',
    'feedback.message': 'Your Feedback',
    'feedback.submit': 'Submit Feedback',
    'theme.dark': 'Dark Mode',
    'theme.light': 'Light Mode',
  },
  hi: {
    'app.title': 'जल मित्र नेटवर्क',
    'app.tagline': 'हर बूंद मायने रखती है—पानी का उपयोग समझदारी से करें',
    'nav.home': 'होम',
    'nav.waterQuality': 'जल गुणवत्ता',
    'nav.agriculture': 'कृषि',
    'nav.education': 'शिक्षा',
    'nav.community': 'समुदाय',
    'nav.darkMode': 'डार्क मोड',
    'stats.waterCrisis': 'जल संकट',
    'stats.population': '600 मिलियन भारतीय उच्च जल तनाव का सामना करते हैं',
    'stats.groundwater': 'भारत का 70% पानी दूषित है',
    'stats.farmers': '80% ताजे पानी का उपयोग कृषि के लिए किया जाता है',
    'home.hero.title': 'जल संरक्षण के आंदोलन में शामिल हों',
    'home.hero.subtitle': 'भारत के जल संसाधनों की रक्षा के लिए सीखें, जुड़ें और कार्रवाई करें',
    'home.hero.cta': 'शुरू करें',
    'home.hero.learnMore': 'और जानें',
    'home.features.title': 'हमारा मिशन',
    'home.features.education': 'शिक्षा',
    'home.features.education.desc': 'जल संरक्षण और टिकाऊ प्रथाओं के बारे में जानें',
    'home.features.tracking': 'गुणवत्ता ट्रैक करें',
    'home.features.tracking.desc': 'अपने क्षेत्र में पानी की गुणवत्ता की निगरानी करें',
    'home.features.community': 'समुदाय',
    'home.features.community.desc': 'कहानियां साझा करें और दूसरों से जुड़ें',
    'home.features.agriculture': 'कृषि',
    'home.features.agriculture.desc': 'सूखा प्रतिरोधी खेती तकनीकों का पता लगाएं',
    'wqi.title': 'जल गुणवत्ता सूचकांक',
    'wqi.description': 'विभिन्न क्षेत्रों में पानी की गुणवत्ता का ट्रैक करें',
    'community.title': 'सामुदायिक कहानियां',
    'community.subtitle': 'वास्तविक लोग जो अंतर ला रहे हैं',
    'community.join': 'आंदोलन में शामिल हों',
    'community.pledge': 'संकल्प लें',
    'community.name': 'नाम',
    'community.email': 'ईमेल',
    'community.yourName': 'आपका नाम',
    'community.yourEmail': 'आपका ईमेल',
    'community.takePledge': 'संकल्प लें',
    'community.pledgeDesc': 'जल संरक्षण का संकल्प लें और हमारे बढ़ते जल संरक्षकों के समुदाय का हिस्सा बनें।',
    'community.communities': 'जुड़े समुदाय',
    'community.litersSaved': 'बचाए गए लीटर',
    'community.farmers': 'समर्थित किसान',
    'community.schools': 'स्कूल कार्यक्रम',
    'footer.rights': 'सर्वाधिकार सुरक्षित',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'education.title': 'शिक्षा संसाधन',
    'education.description': 'शिक्षा जल संरक्षण प्रथाओं में स्थायी परिवर्तन बनाने की कुंजी है। हमारे संसाधन विद्यार्थियों, शिक्षकों और समुदायों के लिए जल मुद्दों और समाधानों के बारे में जानने के लिए डिज़ाइन किए गए हैं।',
    'education.materials': 'शैक्षिक सामग्री',
    'education.quiz.title': 'जल संरक्षण प्रश्नोत्तरी',
    'education.quiz.description': 'जल संरक्षण के बारे में अपने ज्ञान का परीक्षण करें और अपने जल उपयोग को कम करने के तरीके सीखें।',
    'education.quiz.start': 'प्रश्नोत्तरी शुरू करें',
    'education.quiz.next': 'अगला प्रश्न',
    'education.quiz.previous': 'पिछला प्रश्न',
    'education.quiz.submit': 'उत्तर जमा करें',
    'education.quiz.correct': 'सही!',
    'education.quiz.incorrect': 'गलत!',
    'education.quiz.tryAgain': 'और अधिक जानने के लिए फिर से प्रयास करें!',
    'education.quiz.wellDone': 'शाबाश!',
    'education.quiz.yourScore': 'आपका स्कोर:',
    'education.quiz.q1': 'पृथ्वी के कितने प्रतिशत पानी मीठा और मानव उपयोग के लिए उपलब्ध है?',
    'education.quiz.q1.a': 'लगभग 70%',
    'education.quiz.q1.b': 'लगभग 30%',
    'education.quiz.q1.c': '1% से कम',
    'education.quiz.q1.d': 'लगभग 10%',
    'education.quiz.q1.correct': 'c',
    'education.quiz.q2': 'भारत में किस क्षेत्र में सबसे अधिक पानी का उपयोग होता है?',
    'education.quiz.q2.a': 'उद्योग',
    'education.quiz.q2.b': 'कृषि',
    'education.quiz.q2.c': 'घरेलू उपयोग',
    'education.quiz.q2.d': 'ऊर्जा उत्पादन',
    'education.quiz.q2.correct': 'b',
    'education.quiz.q3': 'इनमें से कौन सी जल संरक्षण विधि नहीं है?',
    'education.quiz.q3.a': 'वर्षा जल संचयन',
    'education.quiz.q3.b': 'ड्रिप सिंचाई',
    'education.quiz.q3.c': 'बाढ़ सिंचाई',
    'education.quiz.q3.d': 'जल पुनर्चक्रण',
    'education.quiz.q3.correct': 'c',
    'education.quiz.q4': 'भारत में लगभग कितने लोगों के पास स्वच्छ पानी की पहुंच नहीं है?',
    'education.quiz.q4.a': '100 मिलियन',
    'education.quiz.q4.b': '200 मिलियन',
    'education.quiz.q4.c': '50 मिलियन',
    'education.quiz.q4.d': '80 मिलियन',
    'education.quiz.q4.correct': 'a',
    'education.quiz.q5': 'भारत में जल प्रदूषण का प्रमुख कारण क्या है?',
    'education.quiz.q5.a': 'औद्योगिक कचरा',
    'education.quiz.q5.b': 'कृषि अपवाह',
    'education.quiz.q5.c': 'अनुपचारित सीवेज',
    'education.quiz.q5.d': 'उपरोक्त सभी',
    'education.quiz.q5.correct': 'd',
    'cta.join': 'आज ही जल बचाने के आंदोलन से जुड़ें',
    'agriculture.title': 'स्थायी कृषि',
    'agriculture.description': 'कृषि भारत में मीठे पानी का सबसे बड़ा उपभोक्ता है, जो 80% से अधिक जल उपयोग के लिए जिम्मेदार है। हमारे स्थायी कृषि संसाधन किसानों को फसल उपज बनाए रखते हुए जल-कुशल प्रथाओं को लागू करने में मदद करते हैं।',
    'agriculture.techniques': 'सूखा प्रतिरोधी खेती तकनीक',
    'agriculture.drip': 'ड्रिप सिंचाई',
    'agriculture.drip.desc': 'पौधों की जड़ों तक सीधे पानी पहुंचाकर बाढ़ सिंचाई की तुलना में 60% तक पानी बचाता है।',
    'agriculture.mulching': 'मल्चिंग',
    'agriculture.mulching.desc': 'वाष्पीकरण को कम करता है, खरपतवारों को दबाता है, और मिट्टी के स्वास्थ्य में सुधार करता है।',
    'agriculture.crops': 'सूखा प्रतिरोधी फसलें',
    'agriculture.crops.desc': 'कम पानी की आवश्यकता वाली किस्में जो सूखे समय भी सह सकती हैं।',
    'agriculture.rainwater': 'वर्षा जल संचयन',
    'agriculture.rainwater.desc': 'सूखे अवधि के दौरान सिंचाई के लिए वर्षा जल का संग्रह और भंडारण।',
    'agriculture.network': 'हमारा नेटवर्क किसानों को कृषि विशेषज्ञों से जोड़ता है जो स्थानीय परिस्थितियों और उपलब्ध संसाधनों के आधार पर इन तकनीकों को लागू करने के लिए मार्गदर्शन प्रदान करते हैं।',
    'waterquality.title': 'जल गुणवत्ता',
    'waterquality.description': 'जल गुणवत्ता की निगरानी समुदायों के स्वास्थ्य और सुरक्षा सुनिश्चित करने के लिए आवश्यक है। हमारा जल गुणवत्ता सूचकांक (WQI) भारत के विभिन्न क्षेत्रों में जल गुणवत्ता पर रीयल-टाइम डेटा प्रदान करता है।',
    'waterquality.understanding': 'जल गुणवत्ता सूचकांक को समझना',
    'waterquality.understanding.desc': 'जल गुणवत्ता सूचकांक एक समग्र मापक है जो किसी विशिष्ट क्षेत्र में पानी की समग्र गुणवत्ता को इंगित करता है। यह विभिन्न पैरामीटरों को ध्यान में रखता है जैसे:',
    'waterquality.parameters.ph': 'पीएच स्तर',
    'waterquality.parameters.oxygen': 'घुलित ऑक्सीजन',
    'waterquality.parameters.bod': 'जैव रासायनिक ऑक्सीजन मांग',
    'waterquality.parameters.bacteria': 'कुल कोलिफॉर्म बैक्टीरिया',
    'waterquality.parameters.nutrients': 'नाइट्रेट्स और फॉस्फेट्स',
    'waterquality.parameters.turbidity': 'टर्बिडिटी',
    'waterquality.parameters.tds': 'कुल घुलित ठोस',
    'feedback.title': 'आपकी प्रतिक्रिया महत्वपूर्ण है',
    'feedback.description': 'अपने मूल्यवान इनपुट से हमारे जल संरक्षण प्रयासों में सुधार में मदद करें।',
    'feedback.name': 'नाम',
    'feedback.email': 'ईमेल',
    'feedback.message': 'आपकी प्रतिक्रिया',
    'feedback.submit': 'प्रतिक्रिया भेजें',
    'theme.dark': 'डार्क मोड',
    'theme.light': 'लाइट मोड',
  },
  mr: {
    'app.title': 'जल मित्र नेटवर्क',
    'app.tagline': 'प्रत्येक थेंब महत्वाचा आहे—पाण्याचा वापर विवेकाने करा',
    'nav.home': 'होम',
    'nav.waterQuality': 'पाणी गुणवत्ता',
    'nav.agriculture': 'कृषी',
    'nav.education': 'शिक्षण',
    'nav.community': 'समुदाय',
    'nav.darkMode': 'डार्क मोड',
    'stats.waterCrisis': 'पाणी संकट',
    'stats.population': '600 दशलक्ष भारतीय तीव्र पाणी ताण अनुभवतात',
    'stats.groundwater': 'भारताचे 70% पाणी दूषित आहे',
    'stats.farmers': '80% ताज्या पाण्याचा वापर शेतीसाठी केला जातो',
    'home.hero.title': 'पाणी संवर्धन चळवळीत सामील व्हा',
    'home.hero.subtitle': 'भारताच्या पाणी संसाधनांचे संरक्षण करण्यासाठी शिका, सहभागी व्हा आणि कृती करा',
    'home.hero.cta': 'सुरू करा',
    'home.hero.learnMore': 'अधिक जाणून घ्या',
    'home.features.title': 'आमचे मिशन',
    'home.features.education': 'शिक्षण',
    'home.features.education.desc': 'पाणी संवर्धन आणि शाश्वत पद्धतींबद्दल शिका',
    'home.features.tracking': 'गुणवत्ता ट्रॅक करा',
    'home.features.tracking.desc': 'आपल्या भागातील पाण्याची गुणवत्ता मॉनिटर करा',
    'home.features.community': 'समुदाय',
    'home.features.community.desc': 'कथा शेअर करा आणि इतरांशी कनेक्ट व्हा',
    'home.features.agriculture': 'कृषी',
    'home.features.agriculture.desc': 'दुष्काळ प्रतिरोधक शेती तंत्रांचा शोध घ्या',
    'wqi.title': 'पाणी गुणवत्ता निर्देशांक',
    'wqi.description': 'विविध प्रदेशांतील पाण्याच्या गुणवत्तेचा मागोवा घ्या',
    'community.title': 'समुदाय कथा',
    'community.subtitle': 'खरे लोक फरक घडवत आहेत',
    'community.join': 'चळवळीत सामील व्हा',
    'community.pledge': 'संकल्प करा',
    'community.name': 'नाव',
    'community.email': 'ईमेल',
    'community.yourName': 'तुमचे नाव',
    'community.yourEmail': 'तुमचा ईमेल',
    'community.takePledge': 'संकल्प करा',
    'community.pledgeDesc': 'पाणी संवर्धनाचा संकल्प करा आणि आमच्या वाढत्या पाणी संरक्षकांच्या समुदायाचा भाग बना.',
    'community.communities': 'सहभागी समुदाय',
    'community.litersSaved': 'वाचवलेले लिटर',
    'community.farmers': 'समर्थित शेतकरी',
    'community.schools': 'शाळा कार्यक्रम',
    'footer.rights': 'सर्व हक्क राखीव',
    'footer.privacy': 'गोपनीयता धोरण',
    'footer.terms': 'सेवा अटी',
    'education.title': 'शिक्षण संसाधने',
    'education.description': 'पाणी संवर्धन पद्धतींमध्ये टिकाऊ बदल घडवण्यासाठी शिक्षण महत्वाचे आहे. आमची संसाधने विद्यार्थी, शिक्षक आणि समुदायांसाठी पाणी समस्या आणि उपायांबद्दल शिकण्यासाठी डिझाइन केली आहेत.',
    'education.materials': 'शैक्षणिक साहित्य',
    'education.quiz.title': 'पाणी संवर्धन क्विझ',
    'education.quiz.description': 'पाणी संवर्धनाबद्दल आपल्या ज्ञानाची चाचणी घ्या आणि आपला पाणी वापर कमी करण्याचे मार्ग शिका.',
    'education.quiz.start': 'क्विझ सुरू करा',
    'education.quiz.next': 'पुढचा प्रश्न',
    'education.quiz.previous': 'मागील प्रश्न',
    'education.quiz.submit': 'उत्तरे सबमिट करा',
    'education.quiz.correct': 'बरोबर!',
    'education.quiz.incorrect': 'चुकीचे!',
    'education.quiz.tryAgain': 'अधिक शिकण्यासाठी पुन्हा प्रयत्न करा!',
    'education.quiz.wellDone': 'छान केले!',
    'education.quiz.yourScore': 'तुमचे गुण:',
    'education.quiz.q1': 'पृथ्वीच्या किती पाण्याचा वापर मानवी वापरासाठी गोड्या पाण्यात होतो?',
    'education.quiz.q1.a': 'सुमारे 70%',
    'education.quiz.q1.b': 'सुमारे 30%',
    'education.quiz.q1.c': '1% पेक्षा कमी',
    'education.quiz.q1.d': 'सुमारे 10%',
    'education.quiz.q1.correct': 'c',
    'education.quiz.q2': 'भारतात कोणत्या क्षेत्रात सर्वाधिक पाण्याचा वापर होतो?',
    'education.quiz.q2.a': 'उद्योग',
    'education.quiz.q2.b': 'कृषी',
    'education.quiz.q2.c': 'घरगुती वापर',
    'education.quiz.q2.d': 'ऊर्जा निर्मिती',
    'education.quiz.q2.correct': 'b',
    'education.quiz.q3': 'खालीलपैकी कोणती पाणी संवर्धन पद्धत नाही?',
    'education.quiz.q3.a': 'पावसाचे पाणी संचयन',
    'education.quiz.q3.b': 'ठिबक सिंचन',
    'education.quiz.q3.c': 'पूर सिंचन',
    'education.quiz.q3.d': 'पाणी पुनर्वापर',
    'education.quiz.q3.correct': 'c',
    'education.quiz.q4': 'भारतात किती लोकांना शुद्ध पाणी मिळत नाही?',
    'education.quiz.q4.a': '100 दशलक्ष',
    'education.quiz.q4.b': '200 दशलक्ष',
    'education.quiz.q4.c': '50 दशलक्ष',
    'education.quiz.q4.d': '80 दशलक्ष',
    'education.quiz.q4.correct': 'a',
    'education.quiz.q5': 'भारतातील जल प्रदूषणाचे मुख्य कारण कोणते आहे?',
    'education.quiz.q5.a': 'औद्योगिक कचरा',
    'education.quiz.q5.b': 'शेती प्रवाह',
    'education.quiz.q5.c': 'अप्रक्रिया केलेले सांडपाणी',
    'education.quiz.q5.d': 'वरील सर्व',
    'education.quiz.q5.correct': 'd',
    'cta.join': 'आजच पाणी वाचवण्याच्या चळवळीत सामील व्हा',
    'agriculture.title': 'शाश्वत कृषी',
    'agriculture.description': 'कृषी ही भारतातील गोड्या पाण्याची सर्वात मोठी ग्राहक आहे, जी 80% पेक्षा जास्त पाणी वापरासाठी जबाबदार आहे. आमची शाश्वत कृषी संसाधने शेतकऱ्यांना पीक उत्पादन टिकवून ठेवताना पाणी-कार्यक्षम पद्धती लागू करण्यास मदत करतात.',
    'agriculture.techniques': 'दुष्काळ प्रतिरोधक शेती तंत्रे',
    'agriculture.drip': 'ठिबक सिंचन',
    'agriculture.drip.desc': 'वनस्पतीच्या मुळांपर्यंत थेट पाणी पोहचवून पूर सिंचनाच्या तुलनेत 60% पर्यंत पाणी वाचवते.',
    'agriculture.mulching': 'मल्चिंग',
    'agriculture.mulching.desc': 'बाष्पीभवन कमी करते, तण दाबते आणि मातीचे आरोग्य सुधारते.',
    'agriculture.crops': 'दुष्काळ प्रतिरोधक पिके',
    'agriculture.crops.desc': 'कमी पाण्याची आवश्यकता असलेल्या आणि कोरड्या काळात टिकाऊ शकणाऱ्या प्रजाती.',
    'agriculture.rainwater': 'पावसाचे पाणी संचयन',
    'agriculture.rainwater.desc': 'कोरड्या काळात सिंचनासाठी पावसाचे पाणी गोळा करणे आणि साठवणे.',
    'agriculture.network': 'आमचे नेटवर्क शेतकऱ्यांना कृषी तज्ज्ञांशी जोडते जे स्थानिक परिस्थिती आणि उपलब्ध संसाधनांच्या आधारे या तंत्रांची अंमलबजावणी करण्याबाबत मार्गदर्शन करतात.',
    'waterquality.title': 'पाणी गुणवत्ता',
    'waterquality.description': 'समुदायांचे आरोग्य आणि सुरक्षितता सुनिश्चित करण्यासाठी पाण्याची गुणवत्ता तपासणे आवश्यक आहे. आमचा वॉटर क्वालिटी इंडेक्स (WQI) भारतातील विविध प्रदेशांमधील पाण्याच्या गुणवत्तेवर रिअल-टाइम डेटा प्रदान करतो.',
    'waterquality.understanding': 'वॉटर क्वालिटी इंडेक्स समजून घेणे',
    'waterquality.understanding.desc': 'वॉटर क्वालिटी इंडेक्स हे एक संयुक्त माप आहे जे विशिष्ट क्षेत्रातील पाण्याची एकूण गुणवत्ता दर्शवते. यामध्ये विविध पॅरामीटर्सचा विचार केला जातो जसे:',
    'waterquality.parameters.ph': 'pH पातळी',
    'waterquality.parameters.oxygen': 'विरघळलेला ऑक्सिजन',
    'waterquality.parameters.bod': 'जैवरासायनिक ऑक्सिजन मागणी',
    'waterquality.parameters.bacteria': 'एकूण कोलिफॉर्म बॅक्टेरिया',
    'waterquality.parameters.nutrients': 'नायट्रेट्स आणि फॉस्फेट्स',
    'waterquality.parameters.turbidity': 'टर्बिडिटी',
    'waterquality.parameters.tds': 'एकूण विरघळलेले घनपदार्थ',
    'feedback.title': 'तुमच्या अभिप्रायाचे महत्त्व आहे',
    'feedback.description': 'तुमच्या मौल्यवान अभिप्रायासह आमच्या पाणी संवर्धन प्रयत्नांमध्ये सुधारणा करण्यास मदत करा.',
    'feedback.name': 'नाव',
    'feedback.email': 'ईमेल',
    'feedback.message': 'तुमचा अभिप्राय',
    'feedback.submit': 'अभिप्राय पाठवा',
    'theme.dark': 'डार्क मोड',
    'theme.light': 'लाइट मोड',
  },
};

// Create language provider component
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using language context
export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
